### ISSUE TITLE
Roadmap to Official Gentoo PS2 Support

### ISSUE THREAD

**Issue by immolo** [frno7/gentoo-mipsr5900el#21]
Tracker to help me record progress of where I am and providing some tasks for others to help out on if they can as things like writing ps2 required ebuilds will save me time to work on solving quirky compiling bugs as they crop up.

- [X] Confirm mipsel turple naming
- [X] Submit patches for mips musl support
- [ ] RelEng mipsel3 musl stages added
- [ ] Build new kernel with hdd support and main for testing
- [ ] Create new PoC live media to solve #20 
- [ ] Create ps2-sources ebuild (live and versioned)
- [ ] Add live media creation support to catalyst using the options provided with a stage4 build - https://wiki.gentoo.org/wiki/Catalyst/Stage_Creation
- [ ] Fix wiki docs - https://wiki.gentoo.org/wiki/User:Immolo/GentooPS2
- [ ] Request upstream merge

**Comment by joaco05** [comment]
@immolo Hi, i made some changes to the wiki, this changes are:

a typo (instead of mipsr5900el-unknown-linux-musl it said mipsr5900el-unknown-linux)

changing the list of profiles and the correct profile option

making the /mnt/usb dir before using it

emerging dosfstools before using mkfs.vfat

and using the flag USE="-openmp" (needs a revision dunno if it is necessary but didn't worked without it)

**Comment by immolo** [comment]
> @immolo Hi, i made some changes to the wiki, this changes are:
> 
> two typos (instead of mipsr5900el-unknown-linux-musl it said mipsr5900el-unknown-linux and tar cvfJ instead of cvf)
> 
> changing the list of profiles and the correct profile option
> 
> making the /mnt/usb dir before using it
> 
> emerging dosfstools before using mkfs.vfat
> 
> and using the flag USE="-openmp" (needs a revision dunno if it is necessary but didn't worked without it)

Thank you for your help, I'm been snowed under with fixing upcoming GCC14 issues and accidentally adopting maintaining a DE in Gentoo because it so someone taking the time right now to fix the issues in my passion projects is very much appreciated <3

I left you a note on IRC when you next login but if you could please reupload the final build of of the live image so others can play while I'm stuck on less fun tasks that would be great and hopefully I will be back soon to get the remainder of these tasks although I'd be very happy to work with you to get it done faster if you are interested :)

**Comment by joaco05** [comment]
@immolo Thanks for the help again, i'll be glad to keep working on this.

I'am triying to make a working build but i'm having problems with the init on the wiki, once i get arround it, i will try to make a liveUSB.

If you want to work together i have no problem doing so with IRC for now i'm publishing my chances in here https://github.com/joaco05/linuxPS2/releases.

**Comment by immolo** [comment]
> @immolo Thanks for the help again, i'll be glad to keep working on this.
> 
> I'am triying to make a working build but i'm having problems with the init on the wiki, once i get arround it, i will try to make a liveUSB.
> 
> If you want to work together i have no problem doing so with IRC for now i'm publishing my chances in here https://github.com/joaco05/linuxPS2/releases.

Sure, I can make time for hints and leave notes on irc in #gentoo just login with your username (register it please and request a cloak) which will display when you type any message. I have a bouncer up anything you type my name before when I get a second to check through the backlog.

**Comment by joaco05** [comment]
Also irc is not working properly for me, i always get lots of disconnects and seems that i didn't recieved any messages. i will try if using the matrix irc bridge is any better. Also i dunno what is a cloak i'm not used to irc

**Comment by immolo** [comment]
https://libera.chat/guides/cloaks

It hides your location and other details from other people.

**Comment by joaco05** [comment]
Done, thanks for the help.

**Comment by immolo** [comment]
You also need to type a message in #gentoo try something like "immolo: I updated the wiki page to fix some issues I found" so it doesn't look like you are making random noise or join #gentoo-chat and just say hi.

**Comment by frno7** [comment]
@immolo, would it be useful to make [prebuilt](https://wiki.gentoo.org/wiki/Binary_package_guide) (GPKG) packages for the kernel? Maybe supplied here (or elsewhere) via Git Hub [actions](https://github.com/frno7/linux/actions) too?

**Comment by joaco05** [comment]
> You also need to type a message in #gentoo try something like "immolo: I updated the wiki page to fix some issues I found" so it doesn't look like you are making random noise or join #gentoo-chat and just say hi.

Yeah, it seems that is what happened last time lol.
